#!/usr/bin/env bash
# installs nginx and configures it on a remote server

# update current ubuntu to latest version
sudo apt-get -y update
# install nginx using ubuntu
sudo apt-get -y install nginx
# firewall configuration
sudo ufw allow 'Nginx HTTP'
# create html page
sudo echo "Hello World!" > /var/www/html/index.html
# restart nginx
sudo service nginx restart
