#!/usr/bin/env bash
# Install and configure HAproxy on load balancing server

sudo apt-get -y update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.2
sudo apt-get -y install haproxy=2.2.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                               echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 17272-web-01 54.165.80.58:80 check
   server 17272-web-02 3.90.83.23:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
